Firmware for nodeMCU prototype
lsd-maddrive/smart-dep pull request #23
Opened 2020-04-11 15:20 UTC by KaiL4eK

Resolve #12

2020-04-11 17:43 UTC, Dohako commented
Еще бы понимать что и как делать

2020-04-11 22:15 UTC, KaiL4eK commented
@Dohako если что-то не понятно - можно спросить и вместе разобраться

2020-04-12 06:19 UTC, Dohako commented
@KaiL4eK Да полностью все непонятно) Ты сможешь как-нибудь показать что надо делать в таких случаях? Сделать какую-нибудь фичу, залить ее сюда, затем удалить у себя и показать, как ты сделаешь ревью с нуля?)

2020-04-12 07:58 UTC, KaiL4eK commented
Сможем сегодня созвониться и все обсудить?

2020-04-13 17:37 UTC, Dohako requested changes

2020-04-13 17:37 UTC, Dohako commented on firmware/main.py
> +        msg = {
test

2020-04-13 17:37 UTC, Dohako commented on firmware/main.py
> +global_config = {
test2

2020-04-21 18:51 UTC, serykhelena approved these changes
Правильно я поняла, что адрес для mqtt будет другой? И у тебя код почти дулируется с эмулятором (я понимаю, что на то он и эмулятор (= ), но это нормальная практика? Или есть смысл сделать какие-то общие классы, а дальше уже делить их на прототип и эмулятор?

2020-04-21 18:55 UTC, KaiL4eK commented
> Правильно я поняла, что адрес для mqtt будет другой? И у тебя код почти дулируется с эмулятором (я понимаю, что на то он и эмулятор (= ), но это нормальная практика? Или есть смысл сделать какие-то общие классы, а дальше уже делить их на прототип и эмулятор?

Я бы сделал общий код, но как библиотека json, так и mqtt имеют аналоги в micropython (ujson/umqtt). Может все таки придем к общей схеме, но пока первоначальный вариант такой.

2020-04-21 18:55 UTC, KaiL4eK commented
А по поводу адресов - будет общий сервер, на который все девайсы будут смотреть и отдавать данные.

2020-06-08 17:43 UTC, merged