3 Loggers (docker-compose)
lsd-maddrive/smart-dep pull request #32
Opened 2020-05-02 16:37 UTC by serykhelena

2020-05-02 16:58 UTC, KaiL4eK requested changes

2020-05-02 16:58 UTC, KaiL4eK commented on logger/logger.py
> +            self.buffer = []
Нее, так делать нельзя) Получается, если база зависнет и мы не можем писать по 10 записей - буфер накопится до 100 записей и после слетит. Тогда теряется смысл хранения в период отказа базы

2020-05-02 16:58 UTC, KaiL4eK commented on logger/logger.py
> +        state_json = json.loads(body.decode('utf-8'))
У всех логеров поведение одинаковое - почему не сделать общий callback в основном классе, а из него дергать функции наследников по необходимости?

2020-05-02 16:58 UTC, KaiL4eK commented on logger/logger.py
> +    with open(args.config) as cfg:
Вот это добро по-хорошему надо перенести на окружение. Можно сделать через dotenv или ручками из os.environ забирать

2020-05-02 16:58 UTC, KaiL4eK commented on logger/requirements.txt
> +flask_migrate==2.5.3
Лишнее

2020-05-02 16:58 UTC, KaiL4eK commented on logger/requirements.txt
> +flask_script==2.0.6
Лишнее

2020-05-02 16:58 UTC, KaiL4eK commented on shared/migration_manager.py
> +logger.debug(f"Migration address: {app_config.SQLALCHEMY_DATABASE_URI.split('@')[1].split('/')[0]}")
Зачем сплитить строку? можно просто ее целиком вывести

2020-05-02 20:11 UTC, serykhelena commented on logger/logger.py
> +            self.buffer = []
@KaiL4eK  тогда я не очень понимаю, что ты имел в виду под "пределом хранения"?

2020-05-02 20:15 UTC, serykhelena commented on logger/logger.py
> +        state_json = json.loads(body.decode('utf-8'))
@KaiL4eK поведение да, одинаковое, но я внутри коллбэка создаю объект определённого типа (состояние/команда/конфиг) и заполняю у каждого свои поля... поэтому, мне казалось, что смысла нет несколько строчек запихивать в класс-родитель...

2020-05-02 20:23 UTC, KaiL4eK commented on logger/logger.py
> +            self.buffer = []
Это предел, который ограничивает размер буфера, чтобы не копить записи до бесконечности, иначе попадём в OOM ошибку. Впрочем, можем просто оставить число предела, по достижении которого происходит запись, а в случае ошибки записи просто не чистить буффер.

2020-05-02 20:27 UTC, KaiL4eK requested changes

2020-05-02 20:27 UTC, KaiL4eK commented on logger/config/.env.dev
> +RABBIT_HOST=rabbitmq
Почему нельзя заменить 4 переменных одной строкой подключения? Amqp поддерживает это, как и pika

2020-05-02 20:27 UTC, KaiL4eK commented on emulator/tests/config.py
> +RABBITMQ_URI = 'amqp://rabbitmq:rabbitmq@tigra:5672/%2F'
Зачем здесь эта замена? Эмуляторы и так уже работают на тигре

2020-05-02 20:27 UTC, KaiL4eK commented on logger/logger.py
> +        state_json = json.loads(body.decode('utf-8'))
Да как сказать, тут только создание ORM объекта относится к этому классу, все остальное общее

2020-05-02 20:28 UTC, serykhelena commented on logger/logger.py
> +            self.buffer = []
но тогда ведь память будет уходить? я просто подумала, что это основной критерий..

2020-05-02 20:30 UTC, KaiL4eK requested changes

2020-05-02 20:30 UTC, KaiL4eK commented on logger/config/dev/cfg_config.yml
> +logger:
Вот этим файлы можно удалить

2020-05-02 20:30 UTC, KaiL4eK commented on logger/logger.py
> +        self.TIMEOUT_S = 3.0
Надо вынести наружу в конфигурацию

2020-05-02 20:30 UTC, KaiL4eK commented on logger/logger.py
> +        self.BUFFER_LIMIT = 10
Наружу в конфиг

2020-05-02 20:48 UTC, serykhelena commented on emulator/tests/config.py
> +RABBITMQ_URI = 'amqp://rabbitmq:rabbitmq@tigra:5672/%2F'
Я у себя просто руками запускала его, чтобы логгер тестить. Забыла поменять обратно

2020-05-02 20:51 UTC, serykhelena commented on logger/config/.env.dev
> +RABBIT_HOST=rabbitmq
Просто во всех примерах подключения я видела только использование параметров по отдельности, поэтому и здесь сделала так..

2020-05-02 20:53 UTC, serykhelena commented on logger/config/.env.dev
> +RABBIT_HOST=rabbitmq
я могу сделать одной строкой, но потом мне нужно будет её парсить на части... пока что не нашла, что можно сделать подключение в одну строку.. ещё поищу

2020-05-02 21:07 UTC, KaiL4eK commented on logger/logger.py
> +        self.buffer.append(new_state)
Все таки просто удалить недостаточно, сейчас в случае ошибки записи старые записи не удалятся (что правильно), но новые в буфер продолжат копиться. Так и до OOM недолго)

2020-05-02 21:14 UTC, KaiL4eK commented on logger/config/.env.dev
> +RABBIT_HOST=rabbitmq
https://pika.readthedocs.io/en/stable/modules/parameters.html
URLParameters

2020-05-02 21:14 UTC, KaiL4eK commented on emulator/tests/config.py
> +RABBITMQ_URI = 'amqp://rabbitmq:rabbitmq@tigra:5672/%2F'
Понял, не сразу заметил, что это тест, мой косяк

2020-05-03 07:09 UTC, KaiL4eK commented on logger/logger.py
> +load_dotenv()
Это разве нужно сейчас, при условии, что env грузится в композе и не монтируется в контейнер?

2020-05-03 07:09 UTC, KaiL4eK commented on logger/logger.py
> +    def __init__(self, config, exchange_name, binding_key, session, constants):
Почему бы не сунуть константы в конфиг? По факту получается, что сейчас конфиг - не конфиг, а строка подключения к кролику. Обычно конфиг - это словарь, который содержит в себе всю конфигурацию для класса.

2020-05-03 07:21 UTC, KaiL4eK commented on logger/logger.py
> +    def __init__(self, config, exchange_name, binding_key, session, constants):
Тут ещё дело в том, что константы должны иметь дефолтные значения, так что лучше из получать из конфига с указанием дефолты

2020-05-03 18:07 UTC, KaiL4eK approved these changes

2020-05-03 18:07 UTC, merged