Валидация тестов для АПИ
lsd-maddrive/smart-dep pull request #49
Opened 2020-06-22 17:57 UTC by serykhelena

2020-06-22 19:03 UTC, KaiL4eK requested changes

2020-06-22 19:03 UTC, KaiL4eK commented on api_server/api_v1.py
> +# Test is not written [pytest] because of micropython
Что это значит?)

2020-06-22 19:03 UTC, KaiL4eK commented on api_server/api_v1.py
> +# Test is not written [pytest]
Можно сгенерить рандом, пост, get, и проверить

2020-06-22 19:03 UTC, KaiL4eK commented on api_server/sockets.py
> +    # logger.debug(f'Received config: {config} from {session_id}')
Можно удалить

2020-06-22 19:12 UTC, serykhelena commented on api_server/sockets.py
> +    # logger.debug(f'Received config: {config} from {session_id}')
Прямо весь сокет для stop_states?

2020-07-05 19:23 UTC, KaiL4eK approved these changes

2020-07-05 19:23 UTC, merged